name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to improve?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Use case and alternatives
